// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_buy_space_ship_2 = "CgkIoM_t4t0GEAIQFA"; // <GPGSID>
        public const string achievement_reach_level_50 = "CgkIoM_t4t0GEAIQBA"; // <GPGSID>
        public const string achievement_reach_level_10 = "CgkIoM_t4t0GEAIQAA"; // <GPGSID>
        public const string achievement_catch_5000_sheeps = "CgkIoM_t4t0GEAIQDg"; // <GPGSID>
        public const string achievement_donator = "CgkIoM_t4t0GEAIQFw"; // <GPGSID>
        public const string achievement_reach_level_40 = "CgkIoM_t4t0GEAIQAw"; // <GPGSID>
        public const string achievement_catch_7500_sheeps = "CgkIoM_t4t0GEAIQDw"; // <GPGSID>
        public const string achievement_reach_level_30 = "CgkIoM_t4t0GEAIQAg"; // <GPGSID>
        public const string achievement_snowball_crasher = "CgkIoM_t4t0GEAIQEg"; // <GPGSID>
        public const string achievement_catche_10000_sheeps = "CgkIoM_t4t0GEAIQEA"; // <GPGSID>
        public const string achievement_reach_level_20 = "CgkIoM_t4t0GEAIQAQ"; // <GPGSID>
        public const string achievement_car_crasher = "CgkIoM_t4t0GEAIQEQ"; // <GPGSID>
        public const string achievement_thanks_for_rating_us = "CgkIoM_t4t0GEAIQDQ"; // <GPGSID>
        public const string achievement_buy_spaceship_3 = "CgkIoM_t4t0GEAIQFQ"; // <GPGSID>
        public const string achievement_buy_spaceship_4 = "CgkIoM_t4t0GEAIQFg"; // <GPGSID>
        public const string achievement_catch_2500_sheeps = "CgkIoM_t4t0GEAIQBg"; // <GPGSID>
        public const string achievement_seeking_our_games = "CgkIoM_t4t0GEAIQCw"; // <GPGSID>
        public const string achievement_catch_1000_sheeps = "CgkIoM_t4t0GEAIQBQ"; // <GPGSID>
        public const string achievement_social_media = "CgkIoM_t4t0GEAIQDA"; // <GPGSID>
        public const string leaderboard_most_sheep_caught = "CgkIoM_t4t0GEAIQBw"; // <GPGSID>
        public const string leaderboard_most_money_earned = "CgkIoM_t4t0GEAIQCA"; // <GPGSID>
        public const string leaderboard_obstacles_destroyed = "CgkIoM_t4t0GEAIQEw"; // <GPGSID>
        public const string achievement_curious_player = "CgkIoM_t4t0GEAIQCg"; // <GPGSID>

}

